"""initial

Revision ID: cc9b8755d1a6
Revises: 
Create Date: 2026-05-13 12:17:37.225964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'cc9b8755d1a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('jurisdictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='crawl_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('documents_found', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('doc_type', sa.Enum('html', 'pdf', 'scanned_pdf', name='doc_type_enum'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('authority_tier', sa.Enum('primary', 'secondary', 'guidance', name='authority_tier_enum'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.Column('section_number', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clauses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('clause_number', sa.String(length=50), nullable=True),
    sa.Column('pillar', sa.Enum('pillar_6', 'pillar_7', 'both', 'other', name='pillar_enum'), nullable=False),
    sa.Column('clause_type', sa.Enum('prohibition', 'permission', 'condition', 'exception', 'definition', 'obligation', 'other', name='clause_type_enum'), nullable=False),
    sa.Column('topics', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('flags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('xpath', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clause_id', sa.UUID(), nullable=False),
    sa.Column('source_doc_id', sa.UUID(), nullable=False),
    sa.Column('article', sa.String(length=100), nullable=True),
    sa.Column('section_ref', sa.String(length=100), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('verbatim_snippet', sa.Text(), nullable=False),
    sa.Column('citation_role', sa.Enum('primary', 'supporting', name='citation_role_enum'), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ),
    sa.ForeignKeyConstraint(['source_doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clause_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clause_id', sa.UUID(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conflicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clause_a_id', sa.UUID(), nullable=False),
    sa.Column('clause_b_id', sa.UUID(), nullable=False),
    sa.Column('conflict_type', sa.Enum('contradiction', 'overlap', 'ambiguity', name='conflict_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clause_a_id'], ['clauses.id'], ),
    sa.ForeignKeyConstraint(['clause_b_id'], ['clauses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conflicts')
    op.drop_table('clause_embeddings')
    op.drop_table('citations')
    op.drop_table('clauses')
    op.drop_table('sections')
    op.drop_table('documents')
    op.drop_table('crawl_jobs')
    op.drop_table('jurisdictions')
    # ### end Alembic commands ###


