name: Sync to Hugging Face

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd backend
          git init
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git checkout -b main
          git add .
          git commit -m "Deploy to Hugging Face"
          git push --force https://chanraghul:$HF_TOKEN@huggingface.co/spaces/chanraghul/regscope-backend main
